### ISSUE TITLE
Design with 2 graphs does not always display correctly

### ISSUE THREAD

**Issue by tmac2470** [tmac2470/SnapLabs#12]
If an experiment is designed on the server and downloaded, it sometimes will not display the graphs as designed.

A possible link is that if "Graph" is selected (dragged and dropped into the space) without the "Data option being selected, the graph is not displayed.

The system should allow for the graph to be displayed if graph setting is  "on" even if the "Data" setting is not "on" for a specific sensor

(See the difference in displays between the experiments on the server "Temp and Accel" and "Temp accel (with data)"

**Comment by jordanow** [comment]
Was fixed. Please open if persists.
