### ISSUE TITLE
Grid Display - Data Collection for more than one sensor

### ISSUE THREAD

**Issue by tmac2470** [tmac2470/SnapLabs#16]
If data from more than one sensor is being collected, then each block of a grid should display values from both sensors. Currently when a Sensor Tag button is pressed, the grid is completed sequentially, and if a second Sensor Tag is used and its button pressed, the next grid block is used.  Instead, each grid should be divided into two sections, one for each Sensor Tag, and the grid positions of each should be incremented only when that SensorTag is used.

Additionally, if data from more than one sensor is being collected, this should be displayed at each click (eg temperature and luxometer values in the classroom light investigation, currently luxometer values do not display).

**Comment by jordanow** [comment]
Fixed
