### ISSUE TITLE
Data Capture

### ISSUE THREAD

**Issue by tmac2470** [tmac2470/SnapLabs#17]
When multiple values are being captured (eg x,y and z co-ords) they should be separated rather than a single string so they can be viewed more easily in Excel.

**Comment by jordanow** [comment]
Fixed with commits https://github.com/tmac2470/SnapLabs/commit/7855bd6a4008bef10188f5ebd89d16f4d1874933 and https://github.com/tmac2470/SnapLabs/commit/132338ae81f4f17db94414667c2c34e4af35e3da
