### ISSUE TITLE
Graph information from the configuration file

### ISSUE THREAD

**Issue by tmac2470** [tmac2470/SnapLabs#19]
The investigation display should read information such as graph and axis titles etc from the experiment configuration file.  
Additionally, only those sensors specified in the configuration file are to be shown (eg if ambient temperature is not selected, it should not be displayed).

**Comment by jordanow** [comment]
Fixed with https://github.com/tmac2470/SnapLabs/commit/6550682120334a2c6299c8ea058f9609bc14edae
