### ISSUE TITLE
Sample Interval specification not working

### ISSUE THREAD

**Issue by tmac2470** [tmac2470/SnapLabs#7]
If the experiment is designed with a higher sampling rate, this is not implemented when the experiment is run.  The experiment should read the set sampling interval from the configuration file and use this for displaying data (this is done by setting the period characteristic for the sensor).

**Comment by jordanow** [comment]
Adding sampling rate (by adding debounceTime) on each sensor's value causes the connection to stop working. Luxometer's issue specified in #16 is one such example. Removing the sampling rate fixes the #16 issue.
Reopening this issue to fix later.

**Comment by tmac2470** [comment]
Concerning the sampling interval, this was previously done by writing to the "Period" portion of the specific sensor 'characteristic' such as described in http://processors.wiki.ti.com/index.php/CC2650_SensorTag_User%27s_Guide#IR_Temperature_Sensor.

**Comment by jordanow** [comment]
Fixed
